[package]
name = "yaar"
license = "MIT"
version = "0.2.0"
edition = "2021"
authors = ["kprotty"]

[features]
default = []
full = ["rt"]

io = ["tokio"]
fs = ["io", "libc"]
net = ["io", "libc"]
sync = ["libc"]
time = ["libc"]
rt = ["libc", "num_cpus"]

[dependencies]
libc = { version = "0.2", optional = true }
num_cpus = { version = "1", optional = true }
tokio = { version = "1", features = ["io-util"], optional = true }
