[package]
name = "yaar"
version = "0.2.0"
authors = ["kprotty"]
edition = "2018"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/kprotty/yaar/"
categories = ["network-programming", "asynchronous", "concurrency", "no-std"]
keywords = ["io", "async", "await", "non-blocking", "futures", "no-std", "thread", "mutex"]
description = """
Yet another asynchronous runtime 
optimized around configuration and no_std.
"""

[features]
default = ["full"]
full = ["os", "future", "sync"]
sync = ["lock_api"]
future = ["futures-core"]
os = [
    "libc",
    "winapi/winbase",
    "winapi/handleapi",
    "winapi/libloaderapi",
]

[dependencies]
lock_api = { version = "0.3", optional = true }
futures-core = { version = "0.3", optional = true, default-features = false }

[target.'cfg(unix)'.dependencies]
libc = { version = "0.2", optional = true, default-features = false }

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", optional = true, default-features = false }

[package.metadata.playground]
features = ["full"]

[package.metadata.docs.rs]
all-features = true

[lib]
name = "yaar"

[dev-dependencies]
num_cpus = "1.11"
parking_lot = "0.10"
criterion = "0.3"
crossbeam-utils = "0.7"

[[bench]]
name = "sync_mutex"
harness = false
