[package]
name = "yaar"
license = "MIT"
version = "0.2.0"
edition = "2018"
authors = ["kprotty"]

[features]
default = []
full = ["rt", "net", "sync"]

rt = ["num_cpus"]
net = ["mio", "io"]
io = ["tokio"]
sync = []

[dependencies]
mio = { version = "0.7", features = ["net", "os-poll"], optional = true }
num_cpus = { version = "1", optional = true }
tokio = { version = "1", optional = true }