[package]
name = "yaar"
version = "0.1.0"
edition = "2018"
authors = ["kprotty <kbutcher6200@gmail.com>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/kprotty/yaar"
categories = ["no-std", "asynchronous", "concurrency", "network-programming"]
keywords = ["io", "async", "await", "non-blocking", "futures", "no-std", "thread", "mutex"]
description = """
Yet another asynchronous runtime 
optimized around configuration and no_std.
"""

[features]
default = []
nightly = []
std = ["os"]
full = ["runtime", "sync", "io", "std"]

io = ["os"]
os = []
core = []
sync = []
runtime = ["core", "os"]

[dependencies]

[package.metadata.playground]
features = ["full"]

[package.metadata.docs.rs]
all-features = true