[package]
name = "zap"
version = "0.1.0"
authors = ["kprotty"]
edition = "2018"
license = "Apache-2.0/MIT"
readme = "README.md"
repository = "https://github.com/kprotty/yaar"
description = """
Yet another asynchronous runtime 
optimized around configuration and no_std.
"""
categories = ["asynchronous", "concurrency", "network-programming"]
keywords = ["io", "async", "await", "non-blocking", "futures", "no-std"]

[features]
default = ["std", "os-platform"]
std = []
os-platform = ["libc", "winapi"]

[target.'cfg(unix)'.dependencies.libc]
optional = true
version = "0.2"
default-features = false

[target.'cfg(windows)'.dependencies.winapi]
optional = true
version = "0.3"
default-features = false
features = [
    "winbase",
    "minwindef",
    "sysinfoapi",
    "processthreadsapi",
]
