[package]
name = "yaar"
version = "0.1.0"
edition = "2018"
authors = ["kprotty <kbutcher6200@gmail.com>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/yaar"
homepage = "https://github.com/kprotty/yaar"
repository = "https://github.com/kprotty/yaar"
categories = [
  "no-std",
  "concurrency",
  "asynchronous",
  "network-programming",
]
keywords = [
  "no-std", "windows", "linux", "unix",
  "thread", "mutex", "lock", "rwlock",
  "async", "await", "non-blocking", "futures",
  "io", "iocp", "io_uring", "epoll", "kevent",
]
description = """
Yet another asynchronous runtime 
optimized around configuration and no_std.
"""

[features]
default = []
nightly = []
std = ["os"]
full = ["std", "executor"]

os = []
executor = []

[package.metadata.playground]
features = ["full"]

[package.metadata.docs.rs]
all-features = true