[package]
name = "yaar"
license = "MIT"
version = "0.4.0"
edition = "2021"

[features]
default = []
full = ["io-util", "net", "time", "sync", "rt"]

io-util = ["tokio/io-util"]
sync = []
time = ["pin-project-lite"]
net = [
    "arc-swap",
    "mio/net",
    "mio/os-poll",
]
rt = [
    "gcd",
    "pin-utils",
    "crossbeam-deque"
]

[dependencies]
tokio = "1"
mio = { version = "0.8", optional = true }
gcd = { version = "2", optional = true }
arc-swap = { version = "1", optional = true }
num_cpus = { version = "1", optional = true }
pin-utils = { version = "0.1", optional = true }
pin-project-lite = { version = "0.2", optional = true }
crossbeam-deque = { version = "0.8", optional = true }
