[package]
name = "yaar"
license = "MIT"
version = "0.2.0"
edition = "2021"
authors = ["kprotty"]

[dependencies]
tokio = { version = "1" }
num_cpus = { version = "1" }
mio = { version = "0.7", features = ["net", "os-poll"] }