[package]
name = "yaar"
license = "MIT"
version = "0.2.0"
edition = "2021"

[features]
default = ["full", "fast"]

full = ["io", "io-util", "net", "sync", "time", "fs", "rt"]
fast = ["crossbeam-deque", "try-lock", "parking_lot", "pin-utils"]

io = ["tokio"]
io-util = ["tokio/io-util"]
net = ["io", "mio/net", "mio/os-poll", "once_cell"]
sync = ["once_cell"]
time = ["once_cell"]
fs = []
rt = ["num_cpus", "once_cell"]

[dependencies]
mio = { version = "0.8", optional = true }
tokio = { version = "1", optional = true }
num_cpus = { version = "1", optional = true }
once_cell = { version = "1", optional = true }
try-lock = { version = "0.2", optional = true }
pin-utils = { version = "0.1", optional = true }
parking_lot = { version = "0.11", optional = true }
crossbeam-deque = { version = "0.8", optional = true }