[package]
name = "yaar"
license = "MIT"
version = "0.2.0"
edition = "2021"
authors = ["kprotty"]

[dependencies]
num_cpus = { version = "1" }
parking_lot = { version = "0.11" }
tokio = { version = "1", features = ["io-util"] }
