[package]
name = "yaar"
license = "MIT"
version = "0.4.0"
edition = "2021"

[features]
default = []
full = ["io", "net", "time", "rt"]

io = ["yaar-io"]
net = ["yaar-net"]
time = ["yaar-time"]
rt = ["yaar-runtime"]

[dependencies]
yaar-io = { path = "./yaar-io", optional = true }
yaar-net = { path = "./yaar-net", optional = true }
yaar-time = { path = "./yaar-time", optional = true }
yaar-runtime = { path = "./yaar-runtime", optional = true }