[package]
name = "yaar-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
gcd = "2"
num_cpus = "1"
try-lock = "0.2"
pin-utils = "0.1"
parking_lot = "0.11"
crossbeam-deque = "0.8"
yaar-waker = { path = "../yaar-waker" }