[package]
name = "yaar-lock"
version = "0.1.3-alpha.1"
authors = ["kprotty"]
edition = "2018"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/kprotty/yaar/tree/master/yaar-lock"
categories = ["concurrency", "no-std"]
keywords = ["no-std", "thread", "mutex"]
description = """
Fast, no_std synchronization primitives.
"""

[features]
default = ["os", "sync", "async"]
os = ["libc", "winapi"]
sync = ["lock_api"]
async = []

[dependencies.lock_api]
optional = true
version = "0.3"

[target.'cfg(unix)'.dependencies.libc]
optional = true
version = "0.2"
default-features = false

[target.'cfg(windows)'.dependencies.winapi]
optional = true
version = "0.3"
default-features = false
features = [
    "winbase",
    "handleapi",
    "libloaderapi",
]
