[package]
name = "yaar-lock"
version = "0.3.0"
authors = ["kprotty"]
edition = "2018"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/kprotty/yaar/tree/master/yaar-lock"
categories = ["concurrency", "no-std"]
keywords = ["no-std", "thread", "mutex"]
description = """
Fast, no_std synchronization primitives.
"""

[features]
default = []
full = ["os", "sync", "future"]

# Main features for yaar-lock
os = []
sync = ["lock_api"]
future = ["sync", "futures-intrusive"]

[dependencies]
lock_api = { optional = true, version = "0.3" }
futures-intrusive = { optional = true, version = "0.3", default-features = false }

[package.metadata.docs.rs]
features = ["full", "nightly"]

[package.metadata.playground]
features = ["full"]
