[package]
name = "yaar-lock"
version = "0.2.0"
authors = ["kprotty"]
edition = "2018"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/kprotty/yaar/tree/master/yaar-lock"
categories = ["concurrency", "no-std"]
keywords = ["no-std", "thread", "mutex"]
description = """
Fast, no_std synchronization primitives.
"""

[features]
default = ["os", "sync", "futures"]
sync = ["lock_api"]
futures = []
os = [
    "libc",
    "winapi/winbase",
    "winapi/handleapi",
    "winapi/libloaderapi",
]

[dependencies.lock_api]
optional = true
version = "0.3"

[target.'cfg(unix)'.dependencies.libc]
optional = true
version = "0.2"
default-features = false

[target.'cfg(windows)'.dependencies.winapi]
optional = true
version = "0.3"
default-features = false

[lib]
name = "yaar_lock"

[dev-dependencies]
num_cpus = "1.11"
parking_lot = "0.10"
futures-intrusive = "0.2"
criterion = "0.3"
async-std = "1.4"
tokio = { version = "0.2", features = ["sync", "rt-threaded"] }

[[bench]]
name = "async_mutex"
harness = false
