[package]
name = "yaar-lock"
version = "0.2.0"
authors = ["kprotty"]
edition = "2018"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/kprotty/yaar/tree/master/yaar-lock"
categories = ["concurrency", "no-std"]
keywords = ["no-std", "thread", "mutex"]
description = """
Fast, no_std synchronization primitives.
"""

[features]
default = ["os", "sync", "future"]
nightly = []
sync = ["lock_api"]
future = ["futures-core"]
os = [
    "libc",
    "winapi/winbase",
    "winapi/handleapi",
    "winapi/libloaderapi",
]

[dependencies]
lock_api = { version = "0.3", optional = true }
futures-core = { version = "0.3", optional = true, default-features = false }

[target.'cfg(unix)'.dependencies]
libc = { version = "0.2", optional = true, default-features = false }

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", optional = true, default-features = false }

[dev-dependencies]
num_cpus = "1.11"
parking_lot = "0.10"
futures-intrusive = "0.3"
criterion = "0.3"
async-std = "1.4"
crossbeam-utils = "0.7" 
tokio = { version = "0.2", features = ["sync", "rt-threaded"] }

[lib]
name = "yaar_lock"

[[bench]]
name = "async_mutex"
harness = false

[[bench]]
name = "sync_mutex"
harness = false

[package.metadata.docs.rs]
all-features = true
