[package]
name = "yaar-sys"
version = "0.1.0"
authors = ["kprotty"]
edition = "2018"
description = """
System definitions for platforms supported by the yaar crate ecosystem
"""

[target.'cfg(unix)'.dependencies.libc]
version = "0.2"
default-features = false